# Auto-generated by DataMappingCopilot (Phase-2 ETL Automation) using AI/LLM
from pyspark.sql import SparkSession, functions as F, Window

spark = SparkSession.builder.appName("Bank_ETL").enableHiveSupport().getOrCreate()

df_aa_arr_charge = spark.table("AA.ARR.CHARGE")
df_bank_aa_arr_charge = df_aa_arr_charge.select(
    F.col("ARRANGEMENT.KEY").alias("bank_code"),
    F.col("ACTIVITY").alias("bank_institution_type"),
    F.col("API.ATTRIBUTE").alias("bank_name"),
    F.col("API.ATTRIBUTE").alias("bank_short_name"),
    F.col("ARRANGEMENT.KEY").alias("parent_bank_code")
)

dfs = [df_bank_aa_arr_charge]
final_df = dfs[0]
for df in dfs[1:]:
    final_df = final_df.unionByName(df)

final_df.write.mode("overwrite").format("delta").saveAsTable("edm.bank")