# Auto-generated by DataMappingCopilot (Phase-2 ETL Automation) using AI/LLM
# Target EDM Entity: covenant_balance
# Pattern: UNION (multiple sources combined vertically)
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, to_date
spark = SparkSession.builder.appName("datamappingcopilot_etl_covenant_balance").getOrCreate()
df_sttm_covenant = spark.table("source.STTM_COVENANT")
df_sttm_facility_master = spark.table("source.STTM_FACILITY_MASTER")
df_covenant = df_sttm_covenant.select(col("COVENANT_ID").alias("covenant_balance_id"), lit(None).cast("string").alias("host_covenant_code"))
df_facility = df_sttm_facility_master.select(lit(None).cast("string").alias("covenant_balance_id"), col("BASE_RATE_CODE").alias("host_covenant_code"))
df_union = df_covenant.unionByName(df_facility)
df_union.write.format("delta").mode("overwrite").saveAsTable("edm.covenant_balance")