# Auto-generated by DataMappingCopilot (Phase-2 ETL Automation) using AI/LLM
# Target EDM Entity: credit_application
# Pattern: SINGLE SOURCE (no UNION required)
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, to_date, coalesce

spark = SparkSession.builder.appName("datamappingcopilot_etl_credit_application").getOrCreate()

df = spark.table("source.CARD.ISSUE")

df_transformed = df.select(
    col("CURRENCY").alias("application_currency_code"),
    to_date(coalesce(col("COB.DATE"), col("ISSUE.DATE"))).alias("approval_date"),
    to_date(coalesce(col("NEW.REPAY.DATE"), col("B.PASSPORT.EXP"))).alias("approval_validity_date"),
    col("AUTHORISER").alias("approver_employee_id"),
    col("BPM.MAKER").alias("bank_employee_id"),
    col("CURRENCY").alias("base_currency_id"),
    col("CO.CODE").alias("bu_id"),
    to_date(col("CANCELLATION.DATE")).alias("cancellation_date")
)

df_transformed.write.format("delta").mode("overwrite").saveAsTable("edm.credit_application")